FROM tomcat:jre8
MAINTAINER BSI-Business-Systems-Integration-AG

ADD org.thethingsnetwork.zrh.monitor.ui.html.app.dev-1.0.0-SNAPSHOT.war /usr/local/tomcat/webapps/ttn-monitor.war

CMD ["catalina.sh", "run"]